---
title: "Code-Red_module6"
author: "Liz Aspirino, Tingwei Hu, James Kim, Justin Lau"
date: "2022-11-02"
output: html_document
bibliography: BIOL3140.bib
nocite: '@*'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, packages, include=FALSE}
library(tidyverse)
library(Momocs)
library(knitr)
library(vroom)
library(ape)
```
#Introduction

#Methods

```{r, preprocessing, results='hide'}
#read files and make matrix
f <- list.files("class_out_data",pattern=".txt|.csv",full.names = TRUE)
out <- read_delim(f[1],delim="\t") %>% 
  as.matrix()
#transform matrix in momocs outline
out %>% 
  list() %>% 
  Out() %>% 
  coo_flipx()
```

```{r, loading files & more preprocessing, results='hide'}
#make a large df with vroom
out.df <- vroom::vroom(f, id = "filename")
#add wing info
out.df <- out.df %>% 
  mutate(wing=gsub("XY_.+_(hindwing|forewing)\\..+","\\1",basename(filename))) %>% 
  na.omit()
#make list
outs.l <- sapply(f,function(x) out.df %>% filter(filename==x) %>% select(X,Y) %>% as.matrix)
#extract wing info
wings <- gsub("XY_.+_(hindwing|forewing)\\..+","\\1",basename(names(outs.l)))
outs <-  outs.l %>% 
  Out(fac=list(wing=wings)) %>% 
  coo_flipx() %>% 
  stack() #visualize both wings uncorreced for size
```

```{r, Separate and Procrustes transform both wings}
#separate outlines by fore&hind wing
forewings <- outs %>% 
  filter(wing=="forewing")
hindwings <- outs %>% 
  filter(wing=="hindwing")
#Procrustes, align
fore.min <- forewings %>% 
  coo_nb() %>% 
  min()
forewings %>%
  coo_interpolate(fore.min) %>% 
  fgProcrustes() %>% 
  stack() #visualize forewings
hind.min <- hindwings %>% 
  coo_nb() %>% 
  min()
hindwings %>% 
   coo_interpolate(hind.min) %>% 
  coo_slide(id=1) %>% 
   coo_align()  %>%
  fgProcrustes() %>%
  stack() #visualize hindwings
```
```{r,}

```

#Results

#Discussion

#Author Contributions

#References